language: python

python:
- '2.7'
- '3.6'
- '3.7'

sudo: false

env:
  PYTHONPATH: :test
  PYTHONIOENCODING: utf-8

install:
- pip install -r requirements.txt

script:
- tox
- tox -e flake8
- pylint *.py resources/lib/ test/
- make check-translations
#- kodi-addon-checker . --branch=leia
- coverage run -m unittest discover

after_success:
- codecov
