language: python

python:
- '2.7'
- '3.6'
- '3.7'

sudo: false

env:
  PYTHONPATH: :test
  PYTHONIOENCODING: utf-8

install:
- pip install -r requirements.txt

script:
- make check-pylint
- make check-tox
- make check-translations
#- make check-addon
- make test

after_success:
- codecov
